# Main Tiltfile to bootstraping all services

include('../../../../config-service/Tiltfile')
include('../../../../catalog-service/Tiltfile')
include('../../../../order-service/Tiltfile')

k8s_yaml(['../../platform/development/services/postgresql.yml'])

k8s_resource('catalog-service', resource_deps=['config-service', 'polar-postgres'])
k8s_resource('order-service', resource_deps=['config-service', 'polar-postgres'])
